# Generated by Django 3.2 on 2024-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_food_imagepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoga_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='', verbose_name='Upload Image')),
                ('description', models.TextField(max_length=2000)),
                ('min_val_bmi', models.CharField(max_length=100)),
                ('max_val_bmi', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=300)),
            ],
        ),
    ]
